#!/bin/bash -eux

echo '> Pre-Downloading Docker Containers'

TKG_REPO=registry.tkg.vmware.run
#TKG_REPO=gcr.io/kubernetes-development-244305

CONTAINERS=(
${TKG_REPO}/antrea/antrea-debian:v0.9.3_vmware.1
${TKG_REPO}/azure-cloud-controller-manager:v0.5.1_vmware.2
${TKG_REPO}/azure-cloud-node-manager:v0.5.1_vmware.2
${TKG_REPO}/calico-all/cni-plugin:v3.11.3_vmware.1
${TKG_REPO}/calico-all/kube-controllers:v3.11.3_vmware.1
${TKG_REPO}/calico-all/node:v3.11.3_vmware.1
${TKG_REPO}/calico-all/pod2daemon:v3.11.3_vmware.1
${TKG_REPO}/ccm/manager:v1.2.1_vmware.1
${TKG_REPO}/cert-manager/cert-manager-cainjector:v0.16.1_vmware.1
${TKG_REPO}/cert-manager/cert-manager-controller:v0.16.1_vmware.1
${TKG_REPO}/cert-manager/cert-manager-webhook:v0.16.1_vmware.1
${TKG_REPO}/cluster-api/capd-manager:v0.3.10_vmware.1
${TKG_REPO}/cluster-api/capd-manager:v0.3.11-13-ga74685ee9_vmware.1
${TKG_REPO}/cluster-api/cluster-api-aws-controller:v0.6.2_vmware.1
${TKG_REPO}/cluster-api/cluster-api-aws-controller:v0.6.3_vmware.1
${TKG_REPO}/cluster-api/cluster-api-azure-controller:v0.4.8-47-gfbb2d55b_vmware.1
${TKG_REPO}/cluster-api/cluster-api-controller:v0.3.10_vmware.1
${TKG_REPO}/cluster-api/cluster-api-controller:v0.3.11-13-ga74685ee9_vmware.1
${TKG_REPO}/cluster-api/cluster-api-vsphere-controller:v0.7.1_vmware.1
${TKG_REPO}/cluster-api/kube-rbac-proxy:v0.4.1_vmware.2
${TKG_REPO}/cluster-api/kubeadm-bootstrap-controller:v0.3.10_vmware.1
${TKG_REPO}/cluster-api/kubeadm-bootstrap-controller:v0.3.11-13-ga74685ee9_vmware.1
${TKG_REPO}/cluster-api/kubeadm-control-plane-controller:v0.3.10_vmware.1
${TKG_REPO}/cluster-api/kubeadm-control-plane-controller:v0.3.11-13-ga74685ee9_vmware.1
${TKG_REPO}/cluster-autoscaler:v1.19.1_vmware.1
${TKG_REPO}/contour:v1.8.1_vmware.1
${TKG_REPO}/coredns:v1.6.7_vmware.6
${TKG_REPO}/coredns:v1.7.0_vmware.5
${TKG_REPO}/csi/csi-attacher:v2.0.0_vmware.2
${TKG_REPO}/csi/csi-livenessprobe:v1.1.0_vmware.8
${TKG_REPO}/csi/csi-node-driver-registrar:v1.2.0_vmware.2
${TKG_REPO}/csi/csi-provisioner:v2.0.0_vmware.1
${TKG_REPO}/csi/volume-metadata-syncer:v2.0.1_vmware.1
${TKG_REPO}/csi/vsphere-block-csi-driver:v2.0.1_vmware.1
${TKG_REPO}/dex:v2.22.0_vmware.2
${TKG_REPO}/envoy:v1.15.0_vmware.1
${TKG_REPO}/etcd:v3.4.13_vmware.4
${TKG_REPO}/etcd:v3.4.3_vmware.11
${TKG_REPO}/fluent-bit:v1.5.3_vmware.1
${TKG_REPO}/gangway:v3.2.0_vmware.2
${TKG_REPO}/grafana/grafana:v7.0.3_vmware.1
${TKG_REPO}/grafana/k8s-sidecar:v0.1.144_vmware.1
${TKG_REPO}/harbor/chartmuseum-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/clair-adapter-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/clair-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/harbor-core:v2.0.2_vmware.1
${TKG_REPO}/harbor/harbor-db:v2.0.2_vmware.1
${TKG_REPO}/harbor/harbor-jobservice:v2.0.2_vmware.1
${TKG_REPO}/harbor/harbor-log:v2.0.2_vmware.1
${TKG_REPO}/harbor/harbor-portal:v2.0.2_vmware.1
${TKG_REPO}/harbor/harbor-registryctl:v2.0.2_vmware.1
${TKG_REPO}/harbor/harbor-toolbox:v2.0.2_vmware.1
${TKG_REPO}/harbor/nginx-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/notary-server-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/notary-signer-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/prepare:v2.0.2_vmware.1
${TKG_REPO}/harbor/redis-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/registry-photon:v2.0.2_vmware.1
${TKG_REPO}/harbor/trivy-adapter-photon:v2.0.2_vmware.1
${TKG_REPO}/kapp-controller:v0.9.0_vmware.1
${TKG_REPO}/kind/node:v1.19.3_vmware.1
${TKG_REPO}/kube-apiserver:v1.18.10_vmware.1
${TKG_REPO}/kube-apiserver:v1.19.3_vmware.1
${TKG_REPO}/kube-controller-manager:v1.18.10_vmware.1
${TKG_REPO}/kube-controller-manager:v1.19.3_vmware.1
${TKG_REPO}/kube-proxy:v1.18.10_vmware.1
${TKG_REPO}/kube-proxy:v1.19.3_vmware.1
${TKG_REPO}/kube-scheduler:v1.18.10_vmware.1
${TKG_REPO}/kube-scheduler:v1.19.3_vmware.1
${TKG_REPO}/kube-vip:v0.2.0_vmware.1
${TKG_REPO}/pause:3.2
${TKG_REPO}/prometheus/alertmanager:v0.20.0_vmware.1
${TKG_REPO}/prometheus/cadvisor:v0.36.0_vmware.1
${TKG_REPO}/prometheus/configmap-reload:v0.3.0_vmware.1
${TKG_REPO}/prometheus/kube-state-metrics:v1.9.5_vmware.1
${TKG_REPO}/prometheus/prometheus:v2.18.1_vmware.1
${TKG_REPO}/prometheus/prometheus_node_exporter:v0.18.1_vmware.1
${TKG_REPO}/prometheus/pushgateway:v1.2.0_vmware.1
${TKG_REPO}/sonobuoy:v0.19.0_vmware.1
${TKG_REPO}/tanzu-connectivity/tanzu-connectivity-binder:v0.2.0_vmware.3
${TKG_REPO}/tanzu-connectivity/tanzu-connectivity-publisher:v0.2.0_vmware.3
${TKG_REPO}/tanzu-connectivity/tanzu-connectivity-registry:v0.2.0_vmware.3
${TKG_REPO}/tkg-connectivity/tanzu-registry-webhook:v1.2.0_vmware.2
${TKG_REPO}/tkg-connectivity/tkg-connectivity-operator:v1.2.0_vmware.2
${TKG_REPO}/tkg-extensions-templates:v1.2.0_vmware.1
${TKG_REPO}/tkg-telemetry:v1.2.0_vmware.1
${TKG_REPO}/tmc-extension-manager:v1.2.0_vmware.1
${TKG_REPO}/velero/data-manager-for-plugin:v1.0.2_vmware.1
${TKG_REPO}/velero/velero-plugin-for-aws:v1.1.0_vmware.1
${TKG_REPO}/velero/velero-plugin-for-microsoft-azure:v1.1.0_vmware.1
${TKG_REPO}/velero/velero-plugin-for-vsphere:v1.0.2_vmware.1
${TKG_REPO}/velero/velero-restic-restore-helper:v1.4.3_vmware.1
${TKG_REPO}/velero/velero:v1.4.3_vmware.1
metallb/speaker:v0.9
metallb/controller:v0.9
mreferre/yelb-ui:0.3
mreferre/yelb-ui:0.6
redis:4.0.2
mreferre/yelb-db:0.3
mreferre/yelb-db:0.5
mreferre/yelb-appserver:0.5
)

for i in ${CONTAINERS[@]};
do
	docker pull $i
done