VSPHERE_SERVER: '10.2.224.4'
VSPHERE_USERNAME: 'cloudadmin@vmc.local'
VSPHERE_PASSWORD: 'FILL-ME-IN'
VSPHERE_DATACENTER: '/SDDC-Datacenter'
VSPHERE_DATASTORE: 'WorkloadDatastore'
VSPHERE_NETWORK: 'tkg-network'
VSPHERE_RESOURCE_POOL: '/SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/TKG'
VSPHERE_FOLDER: '/SDDC-Datacenter/vm/TKG'
VSPHERE_SSH_AUTHORIZED_KEY: "ssh_key"
VSPHERE_TEMPLATE: photon-3-kube-v1.19.3_vmware.1
VSPHERE_DISK_GIB: 30
VSPHERE_NUM_CPUS: 2
VSPHERE_MEM_MIB: 2048
VSPHERE_CONTROL_PLANE_DISK_GIB: "20"
VSPHERE_WORKER_DISK_GIB: "20"
VSPHERE_WORKER_MEM_MIB: "2048"
VSPHERE_CONTROL_PLANE_MEM_MIB: "2048"
VSPHERE_WORKER_NUM_CPUS: "2"
MACHINE_HEALTH_CHECK_ENABLED: "true"
SERVICE_CIDR: "100.64.0.0/13"
CLUSTER_CIDR: "100.96.0.0/11"
TKG_CUSTOM_IMAGE_REPOSITORY: registry.rainpole.io/library
TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY: false
TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZmVENDQTJXZ0F3SUJBZ0lKQUxGN04xV0g5RXFPTUEwR0NTcUdTSWIzRFFFQkRRVUFNRlV4Q3pBSkJnTlYKQkFZVEFsVlRNUk13RVFZRFZRUUlEQXBEWVd4cFptOXlibWxoTVJJd0VBWURWUVFIREFsUVlXeHZJRUZzZEc4eApIVEFiQmdOVkJBTU1GSEpsWjJsemRISjVMbkpoYVc1d2IyeGxMbWx2TUI0WERUSXdNVEl6TURJeU1qYzFNbG9YCkRUTXdNVEl5T0RJeU1qYzFNbG93VlRFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ01Da05oYkdsbWIzSnUKYVdFeEVqQVFCZ05WQkFjTUNWQmhiRzhnUVd4MGJ6RWRNQnNHQTFVRUF3d1VjbVZuYVhOMGNua3VjbUZwYm5CdgpiR1V1YVc4d2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURINVZnSWM2b0l0WS8xCkxGM1lQMWl1WEIxLzdKOHEzblFnQlAycHpvN1Bpc0xsZVBzazBPd2FiTVQ5bjhTcnJtYjlnUUsvTytVaXZST04KZzZlZHpqQS83NlI3T0lKNTBYQTY1VlAvQ3FlMTRGYUgxOWZaWi96SXQ1bVBvOUh4bmNYclU2cGR2MzNkek9qWgo1cWlVSzUrSkV5bG9zU0lUeXRzbVYrMms0UDlEWE5OSXRNTVp5S0FueXlISWF5ZEE4TGFyeUZNUXhIYXYrTXBwCnFRcGJ4NVFxYndMdUNGdEZ0d2lWc2NUY2hjU1N2WkdMZldEV0ZxNFpWKzVncURWUEhnRis4K2NSVWl4OUMvR0UKcmQxZ0FCbjFyWEhwWVdFRlBYbk40VUtEZEdORHJhUzU5cWhCVVpoSmJJbHFKU2RTb0NLOFpkTW9UVS9HckdOUgpTVDdmeHZWdTgxQ1dQVHR6elZlRmtONnloSUlFNjd5cEpqVkdiZmI4QUJ1UGhJamZEeVJpMk1acm5Wa1RETG5aCmlFa0RvTzRqZzhPNzdsQzc3ZTAvQmM1SWxsWlhxNXBBMGEwWWVLelN2VWd3K2JCaTFPZmQzem9LN2plUXMrN08KUzlqZStvalhTUjF5ZzNmMnZKNmxKV01wSnE4end0cXpEeXQ1Y1ZkR25yVTF6cHRDN1QyVk8vYjRUMFU4V1hJNgpKdk9zY3c4MXhNcUMxaTF5dlFXcGdBcXdZNkxXUEkzQjBLSmVrZkFpYnhGTFpvMU1QQXVqeEJId2h5YVNqSytYCktLcDJkQ3RzNXlUNDBBektrZ1l5WGJhdU9OL0Q3bjRHODl1U3hqUlFSTzU4TUpVeEpZcVg4UWZ0eENISHJpL3AKeFluNUZTYVhRYUxzRzJHRXg2azdSSTZOL0ZBYVpRSURBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVV0RjkvTDlaUApoN3JVdkNNcktWc0kwL1lETTd3d0h3WURWUjBqQkJnd0ZvQVV0RjkvTDlaUGg3clV2Q01yS1ZzSTAvWURNN3d3CkRBWURWUjBUQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVEwRkFBT0NBZ0VBczFBdWYxZHBnVWFKQlkzZ0dMUnQKbHdYSlVsQW9ZWW9XcW9YdTBBMjE3bnBlcjZBYXo4Q2NWL1FHcnBsTVlKVUh3b0NmVXBIQi9DNjRYc1lpTGdsUQpiQWx0VGxVajd5YklKdk0rN2Z3cDhjSXpqWlFNTWlxQ2lDbDRaSFpPeTVTZkFzVkcrUnNrWlgzVEoybXdDaGhlCjVBN2JWV013ekhXSDlFcDJMR21Wb29zMVViRENJT0VrM0wrMGhXOS80SDVBYlJ0WlNYcm16bmI1U3NCbmxPUzAKR3hyeWhXRThPc2Y5Rjc5bEREZXFUQVZ1L2dMMVpOV3plektEV01NM3hIakFXQUlCMUJ2clZjUFpjUEJ1ZnViMApEQ3c4ek1XV2poTE12UHFTWjBORE9HcFB5UG5IVUhOQ1kvemNlQlFHenBRdHVmWHJ0dkNBaDlFQlZ5ZjBHT1FzCjNNT1Q0TkYwUHd1UDVlUDBhVDRxbS9oRHhCS2ZLZHdRNThwd0cwdEhOcGcyZTZDd0d0VkVUc29NeHlZaWpETzkKY1haSXVzTHRMYis0Wkx0TjBlYUM3QmhzNlZscTZVVmQwd3BnWnNpQWhieFZwbUgrRis4SWxmbnhkVkpJc0tVKwoza3U3YWQ3bjU1SzJtNzFuS2FOWGtwdzE1K0M0UkhYOEtnUGRteUd3S0Ewak1JazFKV1VQMjd0MzhOOEtSYlhhCmNxeXlqZDJDWlVnaFB1Wm53K0ZqeU1PU2hOd3NJZ0g5WlZSU3o3QlFsdTVqbExuRzRFVzlmOVpMYnlsanUzcVgKU0kxQU9ubUpHR2Q3Y050emE0KzFySk9yYzgvc3hBM0hoeEFkblNWTHFTKzFLRkxNaDQ5cnVXQUhqekFjYW5XSwpiNHYxTjNsTGZrQkd5NkNPR1FQcGJ3ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
cert-manager-timeout: 30m0s
overridesFolder: /root/.tkg/overrides
NODE_STARTUP_TIMEOUT: 20m
BASTION_HOST_ENABLED: "true"
providers:
  - name: cluster-api
    url: /root/.tkg/providers/cluster-api/v0.3.11/core-components.yaml
    type: CoreProvider
  - name: aws
    url: /root/.tkg/providers/infrastructure-aws/v0.6.3/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: /root/.tkg/providers/infrastructure-vsphere/v0.7.1/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: azure
    url: /root/.tkg/providers/infrastructure-azure/v0.4.8/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: tkg-service-vsphere
    url: /root/.tkg/providers/infrastructure-tkg-service-vsphere/v1.0.0/unused.yaml
    type: InfrastructureProvider
  - name: kubeadm
    url: /root/.tkg/providers/bootstrap-kubeadm/v0.3.11/bootstrap-components.yaml
    type: BootstrapProvider
  - name: kubeadm
    url: /root/.tkg/providers/control-plane-kubeadm/v0.3.11/control-plane-components.yaml
    type: ControlPlaneProvider
  - name: docker
    url: /root/.tkg/providers/infrastructure-docker/v0.3.10/infrastructure-components.yaml
    type: InfrastructureProvider
images:
    all:
        repository: registry.tkg.vmware.run/cluster-api
    cert-manager:
        repository: registry.tkg.vmware.run/cert-manager
        tag: v0.16.1_vmware.1
release:
    version: v1.2.1